### ISSUE TITLE
Error when running from npx

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/witnet-requests-js#51]
Command:

```
npx -p witnet-requests witnet-toolkit try-data-request --hex 0a0f120508021a01801a0210022202100b10a0c21e18022090a10f2833308094ebdc03
```

Output:

```
Need to install the following packages:
  witnet-requests
Ok to proceed? (y) y
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated witnet-ethereum-bridge@0.4.3: This package is now named `witnet-solidity-bridge`. Please make sure to update your dependencies in `package.json` accordingly.
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'regenerator-runtime/runtime'
Require stack:
- /home/tomasz/.npm/_npx/e797c5954c8ba1f4/node_modules/witnet-requests/dist/witnet/toolkit.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/tomasz/.npm/_npx/e797c5954c8ba1f4/node_modules/witnet-requests/dist/witnet/toolkit.js:12:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/tomasz/.npm/_npx/e797c5954c8ba1f4/node_modules/witnet-requests/dist/witnet/toolkit.js'
  ]
}
npm ERR! code 1
npm ERR! path /home/tomasz/projects/witnet-rust
npm ERR! command failed
npm ERR! command sh -c witnet-toolkit "try-data-request" "--hex" "0a0f120508021a01801a0210022202100b10a0c21e18022090a10f2833308094ebdc03"

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tomasz/.npm/_logs/2021-11-19T12_06_40_838Z-debug.log

```

**Comment by tmpolaczyk** [comment]
According to @guidiaz this can be fixed by adding `"regenerator-runtime": "^0.13.9"` to dev-dependencies
