### ISSUE TITLE
ERR_INVALID_URL trying RNG requests with witnet-toolkit

### ISSUE THREAD

**Issue by lrubiorod** [witnet/witnet-requests-js#54]
When you try a RNG request with witnet-toolkit:
```
npx -p witnet-requests witnet-toolkit try-data-request --hex 0a0f120508021a01801a0210022202100b10a0c21e18022090a10f2833308094ebdc03
```

You obtain the error code: ERR_INVALID_URL:

```
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at /home/luis/.npm/_npx/e797c5954c8ba1f4/node_modules/witnet-requests/dist/witnet/toolkit.js:475:161
    at Array.map (<anonymous>)
    at _callee7$ (/home/luis/.npm/_npx/e797c5954c8ba1f4/node_modules/witnet-requests/dist/witnet/toolkit.js:445:68)
    at tryCatch (/home/luis/.npm/_npx/e797c5954c8ba1f4/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/home/luis/.npm/_npx/e797c5954c8ba1f4/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/home/luis/.npm/_npx/e797c5954c8ba1f4/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/home/luis/.npm/_npx/e797c5954c8ba1f4/node_modules/witnet-requests/dist/witnet/toolkit.js:38:103) {
  input: '',
  code: 'ERR_INVALID_URL'
}

```

**Comment by aesedepece** [comment]
Lol what's in that request?

**Comment by aesedepece** [comment]
Oh, I see:
```json
{
    "time_lock": 0,
    "retrieve": [
        {
            "kind": "RNG",
            "url": "",
            "script": []
        }
    ],
    "aggregate": {
        "filters": [],
        "reducer": 2
    },
    "tally": {
        "filters": [],
        "reducer": 11
    }
}
```
